use_frameworks!
target 'JMapiOSSDK4.0_Tests' do
  pod 'JMapiOSSDK', :path => '../'
  
  
end

post_install do |installer|
   installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
   end
   end
 end
